language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
env:
  - VUMITEST_REDIS_DB=1 VUMIGO_TEST_DB=postgres VUMI_TEST_TIMEOUT=10 RIAK_VERSION=current
matrix:
  include:
    # Test against the Travis-provided version of Riak (currently 2.0.x).
    # This is a separate matrix inclusion to avoid spawning unnecessary builds.
    - python: "2.7"
      env: VUMITEST_REDIS_DB=1 VUMIGO_TEST_DB=postgres VUMI_TEST_TIMEOUT=10 RIAK_VERSION="1.4.12-1"
services:
  - postgresql
  - redis-server
before_install:
  # Set up an appropriate version of Riak.
  - sudo utils/setup_travis_riak.sh "${RIAK_VERSION}"
  # We need the protobuf-compiler so we can install Riak client libraries.
  - sudo apt-get -qq update
  - sudo apt-get install -qq protobuf-compiler
install:
  - "pip install -r requirements.pip --use-wheel"
  - "pip install -r requirements-dev.pip --use-wheel"
  - "pip install overalls"
  - "npm install"
before_script:
  - "psql -c \"create user go with createdb password 'go';\" -U postgres"
  - "psql -c 'create database go owner go;' -U postgres"
  - "export PYTHONPATH=."
  - "django-admin.py syncdb --migrate --noinput --settings=go.testsettings"
  - "pip list"
  # To see what version of Riak we're running and check that it's happy.
  - riak version
  - sudo riak-admin member-status
script:
  - ./run-tests.sh
  - grunt test
after_script:
  - "psql -c 'drop database go;' -U postgres"
  - "psql -c 'drop user go;' -U postgres"
after_success:
  - overalls --py --lcov mochacov.lcov --lcov coverage/*/lcov.info
